Hw1
nocsland/Python-QA-Engineer pull request #3
Opened 2021-04-12 18:40 UTC by nocsland

Первая версия домашнего задания #1

2021-04-16 06:39 UTC, konflic requested changes
Доведите код до ума, закоментированный код либо раскоментируйте либо удалите, зачем он?

2021-04-16 06:39 UTC, konflic commented on home_work_1/source/Circle.py
> +        if isinstance(figure, Figure):
Хорошо что сделали проверку

2021-04-16 06:39 UTC, konflic commented on home_work_1/source/Figure.py
> +#
Зачем эти комментарии?

2021-04-16 06:39 UTC, konflic commented on home_work_1/tests/test_circle.py
> +from home_work_1.source.Circle import circle
Лучше используйте фикстуры, так делать не нужно

2021-04-16 06:39 UTC, konflic commented on home_work_1/source/Triangle.py
> +triangle = Triangle(name='triangle', base=5, height=6, angles=3, side_a=2, side_b=4, side_c=5)
Этот код не нужно хранить рядом с классом, в этом файле луячше оставить только класс

2021-04-16 06:39 UTC, konflic commented on home_work_1/tests/test_triangle.py
> +# def test_triangle_is_figure():
Зачем столько закомментированного кода

2021-04-16 16:05 UTC, nocsland commented on home_work_1/source/Example.py
> +example = Example()
Даже если этот класс и объект используются в тестах для проверки на то что инстанс не принадлежит к классу Figure?

2021-04-16 16:11 UTC, nocsland commented on home_work_1/source/Figure.py
> +        self.area = area
Сделано

2021-04-20 04:52 UTC, konflic approved these changes
Надо дорабатывать

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Figure.py
> +class Figure:
Все фигуры могут складывать свою площадь с другими, этот метод должен быть общим, я про add_area

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Rectangle.py
> +            return Rectangle.get_rectangle_area(self) + Square.get_square_area(figure)
Нужно делать так `self.area() + figure.area()` я не знаю почему делаете как сейчас, так как у меня в примерах такого точно не блыо.

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Square.py
> +            return print('Передан неправильный класс')
Пересмотрите лекцию по функциональному программированию, return print я тоже никогда не показывал :) даже не очень понятно какова цель такого выражения

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Triangle.py
> +            return print('Передан неправильный класс')
Не используйте в тестах принты вообще

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Square.py
> +    def get_square_area(self):
Каждый метод вычисления площади должен называться просто get_area() без уточнений.

2021-04-20 04:52 UTC, konflic commented on home_work_1/source/Square.py
> +class Square(Figure):
Квадрат это частный случай прямоугольника.

2021-04-21 03:30 UTC, nocsland commented on home_work_1/source/Figure.py
> +class Figure:
Понял, вынесу в базовый класс

2021-04-21 03:31 UTC, nocsland commented on home_work_1/source/Rectangle.py
> +            return Rectangle.get_rectangle_area(self) + Square.get_square_area(figure)
У меня так и было реализовано, но по после вынесения создания объекта в фикстуру, я так и не смог придумать как мне инициализировать атрибут area, если объект создается в фикстуре. Буду признателен, если немного подскажете.

2021-04-21 03:31 UTC, nocsland commented on home_work_1/source/Square.py
> +            return print('Передан неправильный класс')
Спасибо, учту.

2021-04-21 03:32 UTC, nocsland commented on home_work_1/source/Triangle.py
> +            return print('Передан неправильный класс')
Понял, учту.

2021-04-21 03:32 UTC, nocsland commented on home_work_1/source/Square.py
> +    def get_square_area(self):
Исправлю

2021-04-21 03:33 UTC, nocsland commented on home_work_1/source/Square.py
> +class Square(Figure):
Надо подумать, как это реализовать

2021-04-21 17:29 UTC, nocsland commented on home_work_1/source/Figure.py
> +class Figure:
Сделано

2021-04-21 17:30 UTC, nocsland commented on home_work_1/source/Rectangle.py
> +            return Rectangle.get_rectangle_area(self) + Square.get_square_area(figure)
Готово

2021-04-21 17:34 UTC, nocsland commented on home_work_1/source/Triangle.py
> +            return print('Передан неправильный класс')
В данном случае принт в классе, в тестах его нет. Конструкцию return print убрал, оставил просто принт.

2021-04-21 17:35 UTC, nocsland commented on home_work_1/source/Square.py
> +class Square(Figure):
Сделал

2021-04-21 17:36 UTC, nocsland commented on home_work_1/source/Square.py
> +            return print('Передан неправильный класс')
Исправил

2021-04-22 06:04 UTC, konflic approved these changes

2021-04-22 06:04 UTC, konflic commented on home_work_1/source/Square.py
> +class Square(Rectangle, Figure):
Почему множественное наследование? Поизучайте ещё тему, у вас Rectangle уже наследник Figure.

2021-04-22 06:04 UTC, konflic commented on home_work_1/source/Figure.py
> +            print('Передан неправильный класс')
Принты в тестах не используйте никогда.

2021-04-22 06:04 UTC, konflic commented on home_work_1/source/Example.py
> +class Example:
А этот класс я до сих пор не понимаю из какой части задания.

2021-04-22 06:04 UTC, konflic commented on home_work_1/source/Circle.py
> +
Лишняя строка.

2021-04-24 06:44 UTC, nocsland commented on home_work_1/source/Circle.py
> +
Нашел лишнюю строку только в конце, пустую, убрал

2021-04-24 06:44 UTC, nocsland commented on home_work_1/source/Example.py
> +class Example:
Добавил его исключительно для проверки вот этого условия из задания: Если передана не геометрическая фигура, то нужно выдавать ошибку и сообщать что передан неправильный класс. Мне же нужно было передать какой-то объект не относящийся к классу Figure. Если надо реализовать по другому, подскажите пожалуйста, как?

2021-04-24 06:44 UTC, nocsland commented on home_work_1/source/Figure.py
> +            print('Передан неправильный класс')
Это же не в тесте а в классе используется, для проверки условия из задания. Если передана не геометрическая фигура, то нужно выдавать ошибку и сообщать что передан неправильный класс. Возможно я не правильно трактую задание, подскажите пожалуйста, как правильно?

2021-04-24 06:44 UTC, nocsland commented on home_work_1/source/Square.py
> +class Square(Rectangle, Figure):
Исправил

2021-04-24 06:52 UTC, merged